# Generated by Django 4.2.20 on 2025-04-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rabble", "0002_conversation_alter_user_options_user_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="num_likes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="comment",
            name="num_replies",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="post",
            name="num_comments",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="post",
            name="num_likes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="reply",
            name="num_likes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="subrabble",
            name="num_comments",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="subrabble",
            name="num_posts",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
