# Generated by Django 4.2.20 on 2025-04-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rabble", "0005_alter_post_likes_alter_post_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="subrabble",
            name="identifier",
            field=models.TextField(default="identifier"),
        ),
    ]
