# Generated by Django 4.2.20 on 2025-05-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rabble", "0006_subrabble_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subrabble",
            name="identifier",
            field=models.TextField(unique=True),
        ),
    ]
